Rem
Rem $Header: oraolap/admin/xoqu121.sql /main/10 2020/09/10 09:09:57 cjohnson Exp $
Rem
Rem xoqu121.sql
Rem
Rem Copyright (c) 2014, 2020, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      xoqu121.sql - Upgrade the XOQ component to 12.2
Rem
Rem    DESCRIPTION
Rem      Performs any actions necessary to upgrade the XOQ component
Rem      from 12.1 to 12.2
Rem
Rem    NOTES
Rem      None
Rem
Rem    BEGIN SQL_FILE_METADATA 
Rem    SQL_SOURCE_FILE: oraolap/admin/xoqu121.sql 
Rem    SQL_SHIPPED_FILE: olap/admin/xoqu121.sql 
Rem    SQL_PHASE: UPGRADE
Rem    SQL_STARTUP_MODE: UPGRADE
Rem    SQL_IGNORABLE_ERRORS: NONE 
Rem    SQL_CALLING_FILE: oraolap/admin/xoqdbmig.sql
Rem    END SQL_FILE_METADATA
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    cjohnson    09/03/20 - missing shipped_file
Rem    cjohnson    11/09/19 - add missing '-'
Rem    ghicks      07/16/18 - bug 28354015: fix PHASE, STARTUP_MODE metadata
Rem    jcarey      03/08/18 - cleanup
Rem    ddedonat    06/23/15 - Bug 21294751 - Remove redundant call to xoqawmd.sql since
Rem                           xoqsys.sql calls it during upgrade
Rem    mstasiew    04/15/15 - 20345942 proj 58196 revoke select priv for olap
Rem    ddedonat    03/19/15 - Bug 20424899 - Call xoqclnup to cleanup objects that may
Rem                           cause privilege escalation
Rem    dbardwel    01/07/15 - Bug 20315390 for long object identifiers
Rem    cchiappa    08/05/14 - 12.1 update to 12.1 script
Rem    cchiappa    08/05/14 - Created
Rem

@@?/rdbms/admin/sqlsessstart.sql

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_CATALOGS FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_CATALOG_MEASURES FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_PHYS_OBJ FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_PHYS_OBJ_PROP FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_DIMENSIONS FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_ATTRIBUTES FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_CUBES FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_CUBE_DIM_USES FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$AW_DIM_ENABLED_VIEWS FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$AW_CUBE_ENABLED_VIEWS FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$AW_CUBE_ENABLED_HIERCOMBO FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_DIM_LEVELS FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_DIM_HIER_LVL_ORD FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_CUBE_MEASURES FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_CUBE_AGG_SPECS FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_CUBE_AGG_MEAS FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045,-4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_CUBE_AGG_LVL FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'REVOKE SELECT ON olapsys.ALL$OLAP2_AW_CUBE_AGG_OP FROM PUBLIC';
EXCEPTION
 WHEN OTHERS THEN
   IF SQLCODE IN ( -04042, -1927, -942, -4045, -4063 ) THEN NULL;
   ELSE RAISE;
   END IF;
END;
/

-- Call xoqclnup.sql to remove old OLAP Objects that may cause privilege escalation
@@xoqclnup

@@xoqu122

@?/rdbms/admin/sqlsessend.sql
